---
- name: Setup Password for Linux using PAM
  hosts: target_host # Change this to your target hostname or group
  become: yes
  vars:
    repo_url: 'https://github.com/dikshitkhandelwal/Master-Password-Linux.git'
    dest_dir: '/tmp/Master-Password-Linux'
    
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - libpam0g-dev
          - gcc
          - make
          - git
        state: present

    - name: Clone the git repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        clone: yes
        update: yes
      register: git_result

    - name: Fetch the .so file from GitHub
      ansible.builtin.get_url:
        url: "https://github.com/dikshitkhandelwal/Master-Password-Linux/raw/main/pam_mymodule.so"
        dest: "/lib/x86_64-linux-gnu/security/pam_mymodule.so"
        mode: '0644'
      become: yes

    - name: Backup the current common-auth
      ansible.builtin.copy:
        src: /etc/pam.d/common-auth
        dest: /etc/pam.d/common-auth.backup
        remote_src: yes
      become: yes

    - name: Fetch common-auth from GitHub
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/dikshitkhandelwal/Master-Password-Linux/main/common-auth.copy.txt"
        dest: "/etc/pam.d/common-auth"
        mode: '0644'
      become: yes
